#version 450

//still learning, comments may not be 100% corrects
//256 parallel threads
layout(local_size_x = 256) in;

//input arr of floats
layout(set = 0, binding = 0) buffer InBuf {
    float data[];
} inbuf;

//output arr of floats
layout(set = 0, binding = 1) buffer OutBuf {
    float data[];
} outbuf;

layout(push_constant) uniform Push {
    uint N;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.N) return;
    outbuf.data[i] = inbuf.data[i] * 2.0;
}
